baseURL = "/"
languageCode = "en-us"
title = "RootCreator Blog"
theme = "PaperMod"
googleAnalytics = "G-HNJ4XDXZ6C"

[params]
  ShowSearch = true
  defaultTheme = "light" 
  comments = true

  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Sockets and Plugs, Links, about..."

  [[params.socialIcons]]
    name = "Twitter"
    url = "https://twitter.com/rootcreator0"

  [[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/rootcreator"

  [[params.socialIcons]]
    name = "Instagram"
    url = "https://instagram.com/rootcreator"

  [[params.socialIcons]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/rootcreator"

  [params.utterances]
    repo = "pluggedspace/Pluggedspace-blog"  # Your GitHub repo
    issueTerm = "pathname"             # How issues are mapped
    theme = "github-light"
    label = "blog-comments"


[outputs]
  home = ["HTML", "RSS", "JSON"] # JSON is needed for search

[[menu.main]]
  identifier = "Tech Portfolio"
  name = "Tech Portfolio"
  url = "https://rootcreator.github.io/Portfolio-of-the-creator/"
  weight = 1

[[menu.main]]
  identifier = "Work"
  name = "Work"
  url = "https://pluggedspace.org"
  weight = 2

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 3



