baseURL = "https://blog.pluggedspace.org/"
languageCode = "en-us"
title = "Pluggedspace Blog"
theme = "PaperMod"
googleAnalytics = "G-HNJ4XDXZ6C"

[params]
  ShowSearch = true
  defaultTheme = "light" 

  favicon = "pluggedspace.png"

  title = "Pluggedspace Blog"
  description = "Your blog description here"
  author = "Pluggedspace"
  keywords = ["technology", "fintech", "automation"]
  images = ["your-featured-image-url.jpg"]
  disableSpecial1stPost = true
  disableScrollToTop = false
  disableShare = false

  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowWordCount = true
  comments = true
  googleAnalyticsID = "G-HNJ4XDXZ6C"

  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Sockets and Plugs, Links, about..."

  [[params.socialIcons]]
    name = "Twitter"
    url = "https://twitter.com/pluggedspace_io"

  [[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/pluggedspace"

  [[params.socialIcons]]
    name = "Instagram"
    url = "https://instagram.com/pluggedspace"

  [[params.socialIcons]]
    name = "LinkedIn"
    url = "https://linkedin.com/company/pluggedspace"

  

  [params.utterances]
    repo = "pluggedspace/Pluggedspace-blog"  # Your GitHub repo
    issueTerm = "pathname"             # How issues are mapped
    theme = "github-light"  
    label = "blog-comments"

[params.opengraph]
  twitter_cards = true
  facebook = true

[params.seo]
  hideMetadata = false

[outputs]
  home = ["HTML", "RSS", "JSON"] # JSON is needed for search

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "https://pluggedspace.org"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "https://pluggedspace.org/about"
  weight = 2

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "https://blog.pluggedspace.org"
  weight = 3

 [[menu.main]]
  identifier = "services"
  name = "Services"
  url = "https://pluggedspace.org/services"
  weight = 4

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "https://pluggedspace.org/projects"
  weight = 5

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "https://pluggedspace.org/contact/"
  weight = 6




  
