baseURL = "/"
languageCode = "en-us"
title = "RootCreator Blog"
theme = "PaperMod"
googleAnalytics = "G-HNJ4XDXZ6C"

[params]
  ShowSearch = true
  defaultTheme = "light" 

  favicon = "pluggedspace.png"

  title = "Pluggedspace Blog"
  description = "Your blog description here"
  author = "Pluggedspace"
  keywords = ["technology", "fintech", "automation"]
  images = ["your-featured-image-url.jpg"]
  disableSpecial1stPost = true
  disableScrollToTop = false
  disableShare = false

  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowWordCount = true
  comments = true
  googleAnalyticsID = "G-HNJ4XDXZ6C"

  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Sockets and Plugs, Links, about..."

  [[params.socialIcons]]
    name = "Twitter"
    url = "https://twitter.com/rootcreator0"

  [[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/rootcreator"

  [[params.socialIcons]]
    name = "Instagram"
    url = "https://instagram.com/rootcreator"

  [[params.socialIcons]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/rootcreator"

  

  [params.utterances]
    repo = "pluggedspace/Pluggedspace-blog"  # Your GitHub repo
    issueTerm = "pathname"             # How issues are mapped
    theme = "github-light"  
    label = "blog-comments"

[params.opengraph]
  twitter_cards = true
  facebook = true

[params.seo]
  hideMetadata = false

[outputs]
  home = ["HTML", "RSS", "JSON"] # JSON is needed for search

[[menu.main]]
  identifier = "Tech Portfolio"
  name = "Home"
  url = "https://rootcreator.github.io/Portfolio-of-the-creator/"
  weight = 1

[[menu.main]]
  identifier = "Work"
  name = "About"
  url = "https://pluggedspace.org"
  weight = 2

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 3




  
